---
title: "EPPS 6356 Assignment 2"
---


```{r include=FALSE}
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE)
```


### 1. murrell.R


```{r echo = F, out.width = "50%", out.height= "65%"}
### Paul Murrell's R examples (selected)

## Start plotting from basics 
# Note the order
plot(pressure, pch=10)  # Can you change pch?
text(150, 600, 
     "Pressure (mm Hg)\nversus\nTemperature (Celsius)")

#  Examples of standard high-level plots 
#  In each case, extra output is also added using low-level 
#  plotting functions.
# 

# Setting the parameter (3 rows by 2 cols)
par(mfrow=c(3, 2))

# Scatterplot
# Note the incremental additions

x <- c(0.5, 2, 4, 8, 12, 16)
y1 <- c(1, 1.3, 1.9, 3.4, 3.9, 4.8)
y2 <- c(4, .8, .5, .45, .4, .3)

# Setting label orientation, margins c(bottom, left, top, right) & text size
par(las=1, mar=c(4, 4, 2, 4), cex=.7) 
plot.new()
plot.window(range(x), c(0, 6))
lines(x, y1)
lines(x, y2)
points(x, y1, pch=16, cex=4) # Try different cex value?  
points(x, y2, pch=21, bg="blue", cex=2)  # Different background color
par(col="gray50", fg="gray50", col.axis="gray50")
axis(1, at=seq(0, 16, 4)) # What is the first number standing for?
axis(2, at=seq(0, 6, 2))
axis(4, at=seq(0, 6, 2))
box(bty="u")
mtext("Travel Time (s)", side=1, line=2, cex=0.8)
mtext("Responses per Travel", side=2, line=2, las=0, cex=0.8)
mtext("Responses per Second", side=4, line=2, las=0, cex=0.8)
text(4, 5, "Bird 131")
par(mar=c(5.1, 4.1, 4.1, 2.1), col="black", fg="black", col.axis="black")

# Histogram
# Random data
Y <- rnorm(50)
# Make sure no Y exceed [-3.5, 3.5]
Y[Y < -3.5 | Y > 3.5] <- NA # Selection/set range
x <- seq(-3.5, 3.5, .1)
dn <- dnorm(x)
par(mar=c(4.5, 4.1, 3.1, 0))
hist(Y, breaks=seq(-3.5, 3.5), ylim=c(0, 0.5), 
     col="gray80", freq=FALSE)
lines(x, dnorm(x), lwd=2)
par(mar=c(5.1, 4.1, 4.1, 2.1))

# Barplot
par(mar=c(2, 3.1, 2, 2.1)) 
midpts <- barplot(VADeaths, 
                  col=gray(0.1 + seq(1, 9, 2)/11), 
                  names=rep("", 4))
mtext(sub(" ", "\n", colnames(VADeaths)),
      at=midpts, side=1, line=0.5, cex=0.5)
text(rep(midpts, each=5), apply(VADeaths, 2, cumsum) - VADeaths/2,
     VADeaths, 
     col=rep(c("white", "black"), times=3:2), 
     cex=0.8)
par(mar=c(5.1, 4.1, 4.1, 2.1))  

# Boxplot
par(mar=c(3, 4.1, 2, 0))
boxplot(len ~ dose, data = ToothGrowth,
        boxwex = 0.25, at = 1:3 - 0.2,
        subset= supp == "VC", col="white",
        xlab="",
        ylab="tooth length", ylim=c(0,35))
mtext("Vitamin C dose (mg)", side=1, line=2.5, cex=0.8)
boxplot(len ~ dose, data = ToothGrowth, add = TRUE,
        boxwex = 0.25, at = 1:3 + 0.2,
        
        subset= supp == "OJ")
legend(1.5, 9, c("Ascorbic acid", "Orange juice"), 
       fill = c("white", "gray"), 
       bty="n")
par(mar=c(5.1, 4.1, 4.1, 2.1))

# Persp
x <- seq(-10, 10, length= 30)
y <- x
f <- function(x,y) { r <- sqrt(x^2+y^2); 10 * sin(r)/r }
z <- outer(x, y, f)
z[is.na(z)] <- 1
# 0.5 to include z axis label
par(mar=c(0, 0.5, 0, 0), lwd=0.5)
persp(x, y, z, theta = 30, phi = 30, 
      expand = 0.5)
par(mar=c(5.1, 4.1, 4.1, 2.1), lwd=1)

# Piechart
par(mar=c(0, 2, 1, 2), xpd=FALSE, cex=0.5)
pie.sales <- c(0.12, 0.3, 0.26, 0.16, 0.04, 0.12)
names(pie.sales) <- c("Blueberry", "Cherry",
                      "Apple", "Boston Cream", "Other", "Vanilla")
pie(pie.sales, col = gray(seq(0.3,1.0,length=6))) 

# Exercise: Can you generate these charts individually?  Try these functions 
# using another dataset. Be sure to work on the layout and margins
```



### 2. Using the World Wellbeing data

Data is taken from https://happyplanetindex.org/, utilizing table 2 covering all variables.

```{r echo = F, out.width = "50%", out.height= "65%"}

#par()
#lines()
#points()
#axis()
#box()
#text()
#mtext()
#hist()
#boxplot()
#legend()
#persp()
#names()
#pie()

wellbeing = read.csv("~/Desktop/All data-Table 1.csv")

wellbeing = subset(wellbeing, Year == 2019)
wellbeing = subset(wellbeing, Continent > 0)

# Note the order
plot(y = wellbeing$Ladder.of.life..0.10., x = log(wellbeing$Population..thousands.), pch=4,
     xlab = "Log Population", ylab = "Ladder of Life index")


# Scatterplot
# Note the incremental additions

x <- log(wellbeing$Population..thousands.)
y1 <- wellbeing$LifeExp..years.
y2 <- wellbeing$HPI

# Setting label orientation, margins c(bottom, left, top, right) & text size
par(las=1, mar=c(4, 4, 2, 4), cex=.7) 
plot.new()
plot.window(range(x), c(0, 100))
lines(lowess(x, y1), col = "blue")
lines(lowess(x, y2), col = "red")
points(x, y1, pch=21, bg="gold1", cex=2) # Try different cex value?  
points(x, y2, pch=21, bg="darkseagreen", cex=2)  # Different background color
par(col="violetred2", fg="steelblue3", col.axis="coral4")
axis(1, at=seq(0, length(x), 2))
axis(2, at=seq(0, 100, 20))
axis(4, at=seq(0, 60, 20))
box(bty="u")
mtext("Log Population", side=1, line=2, cex=0.8)
mtext("Life Expectancy", side=2, line=2, las=0, cex=0.8)
mtext("HPI", side=4, line=2, las=0, cex=0.8)
text(4, 5, "Bird 131")
par(mar=c(5.1, 4.1, 4.1, 2.1), col="black", fg="black", col.axis="black")

# Histogram
hist((wellbeing$LifeExp..years.), breaks = 40
     ,col = 'blue', lwd = 3,
     xlab = "Life Expactancy")


# Barplot
ggplot(wellbeing, aes( y=Population..thousands., x=Continent)) + 
  geom_bar(position='stack', stat='identity', color = "orange", fill = "black") +
  ggtitle("National Populations by HPI defined 'Continents' ") +
  xlab("Population")


# Persp
x <- seq(-10, 10, length= 30)
y <- x
f <- function(x,y) { r <- sqrt(x^2+y^4); 10 * sin(r)/r }
z <- outer(x, y, f)
z[is.na(z)] <- 1
# 0.5 to include z axis label
par(mar=c(0, 0.5, 0, 0), lwd=0.5)
persp(x, y, z, theta = 30, phi = 30, 
      expand = 0.5,
      main = "x^2, y^4",
      shade = 0.6,
      col = "burlywood1",
      border = "orangered4",
      box = F)
par(mar=c(5.1, 4.1, 4.1, 2.1), lwd=1)

# Piechart
pie(wellbeing$Population..thousands.,
    main = "Country Populations",
    density = 20,
    angle = 30*1:6,
    col = c("blue","red")
    )
```






